trigger:
  branches:
    include:
      - main
  paths:
    include:
      - rpm-auth-ms/**

variables:
  dockerHubConnection: "dockerhub-rpm"
  dockerHubUser: "rjotac"
  imageName: "rpm-auth-ms"
  mavenOpts: "-Dmaven.test.skip=true"

stages:
  - stage: CI
    displayName: "Build & Push Auth Service"
    jobs:
      - job: BuildPush
        pool:
          vmImage: "ubuntu-latest"

        steps:
          - checkout: self
            clean: true

          - task: JavaToolInstaller@0
            inputs:
              versionSpec: "17"
              jdkArchitectureOption: "x64"
              jdkSourceOption: "PreInstalled"

          - task: Maven@3
            displayName: "Build rpm-auth-ms"
            inputs:
              mavenPomFile: "rpm-auth-ms/pom.xml"
              goals: "clean package"
              options: "$(mavenOpts)"
              publishJUnitResults: false

          - task: Docker@2
            displayName: "Build & Push rpm-auth-ms image"
            inputs:
              command: buildAndPush
              containerRegistry: "$(dockerHubConnection)"
              repository: "$(dockerHubUser)/$(imageName)"
              dockerfile: "rpm-auth-ms/Dockerfile"
              buildContext: "rpm-auth-ms"
              tags: |
                latest
                $(Build.BuildId)
